apiVersion: v1
kind: Secret
metadata:
  name: mcp-postgres-secret
  namespace: mcp-prod
type: Opaque
stringData:
  POSTGRES_DB: mcp_postgres_db
  POSTGRES_USER: mcp_user
  POSTGRES_PASSWORD: change_this_password
